### ISSUE TITLE
Can you publish the latest code to npm?

### ISSUE THREAD

**Issue by lokewei** [tb01923/koa-mysql-session#4]
On the npm , the latest version v0.0.2 still had `cleanup` bug

**Comment by tb01923** [comment]
Yeah - let cme see if I can do that this weekend

**Comment by tb01923** [comment]
I just merged the outstanding PR's and pushed to NPM.  I am not really leveraging this anymore, and would welcome assistance on managing this if you are interested.

**Comment by rafmim** [comment]
hi @tb01923 I would be happy to assist in managing.
